---
trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: true
experimentalTernaries: true
bracketSpacing: false
bracketSameLine: true

overrides:
  - files: "*.py"
    options:
      tabWidth: 4
